### PR TITLE
Create separate docker for each feature branch

### PR DESCRIPTION
**Pull request by ggodlewski**

### CODE REVIEW

**Comment by ggodlewski** [comment]
@horner almost done (https://pr-468.wikigdrive.com/) but I need you to configure google console because this domain is not allowed:
image

**Comment by wreiske** [comment]
image

**Comment by wreiske** [comment]
A workaround might be to utilize something like auth.wikigdrive.com as a shared domain, and run a microservice there for all the authentication. 🤔

**Comment by ggodlewski** [comment]
Ok, I'm using dev.wikigdrive.com as a main auth service. Seems to work.

**Review by horner — APPROVED** [review]

**Pull request merged**
