### PR TITLE
Initial conflict logic

### PR DESCRIPTION
**Pull request by ggodlewski**

### CODE REVIEW

**Comment by wreiske** [comment]
image

`npm run test` seems to be failing. Can you take a look @ggodlewski?

**Comment by ggodlewski** [comment]
I've made one small fix. Please, recheck it. Maybe remove dist dir.

On my side fetch clean repo works without any problems:
`git clone https://github.com/gitgis/wikiGDrive.git
cd wikiGDrive
npm install
npm test`

**Comment by wreiske** [comment]
> git clone https://github.com/gitgis/wikiGDrive.git
> cd wikiGDrive
> npm install
> npm test

I tried a complete fresh checkout,
```
~/Documents/prj
$ git clone https://github.com/gitgis/wikiGDrive.git
Cloning into 'wikiGDrive'...
remote: Enumerating objects: 476, done.
remote: Counting objects: 100% (476/476), done.
remote: Compressing objects: 100% (310/310), done.
Receiving obremote: Total 476 (delta 180), reused 416 (delta 141), pack-reused
Receiving objects: 100% (476/476), 1.03 MiB | 4.72 MiB/s, done.
Resolving deltas: 100% (180/180), done.

~/Documents/prj
$ cd wikiGDrive

~/Documents/prj/wikiGDrive (master)
$ npm install

> nodent-runtime@3.2.1 install C:\Users\wreiske\Documents\prj\wikiGDrive\node_modules\nodent-runtime
> node build.js

## Built C:\Users\wreiske\Documents\prj\wikiGDrive\node_modules\nodent-runtime/dist/index.js

> husky@3.0.5 install C:\Users\wreiske\Documents\prj\wikiGDrive\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done

> core-js@2.6.9 postinstall C:\Users\wreiske\Documents\prj\wikiGDrive\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> husky@3.0.5 postinstall C:\Users\wreiske\Documents\prj\wikiGDrive\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 689 packages from 821 contributors and audited 8342 packages in 9.883s
found 0 vulnerabilities


~/Documents/prj/wikiGDrive (master)
$ npm test

> wikigdrive@1.0.0 test C:\Users\wreiske\Documents\prj\wikiGDrive
> mocha-webpack --mode development

 WEBPACK  Compiling...

(node:18136) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 WEBPACK  Compiled successfully in 192ms

 MOCHA  Testing...



  FileStructure
    √ test collisions
    √ test redirects

  LinkTranslatorTest
    1) test convertToRelativePath


  2 passing (7ms)
  1 failing

  1) LinkTranslatorTest
       test convertToRelativePath:

      AssertionError: expected '..\\wiki-g-drive-project-overview.html' to equal '../wiki-g-drive-project-overview.html'
      + expected - actual

      -..\wiki-g-drive-project-overview.html
      +../wiki-g-drive-project-overview.html

      at Context.it (webpack:///./test/LinkTranslatorTest.js?:19:49)



 MOCHA  Tests completed with 1 failure(s)

npm ERR! Test failed.  See above for more details.

~/Documents/prj/wikiGDrive (master)
```

**Comment by wreiske** [comment]
FYI, I think this is due to the difference in Linux / OSX / Windows directory structures... I solved this locally by using path.join.

**Example:**
```
assert.equal(linkTranslator.convertToRelativePath('resources', 'resources/Diagram.svg'), path.join('..', 'resources'));
```

```
  convertToRelativePath(localPath, basePath) {
    const dirName = path.dirname(basePath);

    if (dirName === localPath) {
      return path.join('..', dirName);
    }

    return path.relative(dirName, localPath);
  }
```

**Comment by ggodlewski** [comment]
This way you changed test expected value. You could disable the test as well.
For urls path doesn't work under windows. I changed it to relate-url lib.

**Pull request merged**
